### ISSUE TITLE
[Bug] Loading params from yaml via roslaunch and <rosparam> not consistent with roscore

### ISSUE THREAD

**Issue by HWiese1980** [roshub/vapor_master#25]
Hi folks,

looks like I have found another bug. I have a YAML file that looks like this:

    joints: 
      - (JointA, 0)
      - (JointB, 1)
      - (JointC, 16)

...basically. 

When I load this YAML file in a launch file by means of `<rosparam command="load" file="...` and fetch the parameters afterwards with `rosparam get joints` I get the following returned from `roscore`: 

    ['(JointA, 0)', '(JointB, 1)', '(JointC, 16)']

... which obviously is a list.

But when I try to do that with `vapor_master` I get the following:

    {'0': '(JointA, 0)', '1': '(JointB, 1)', '2': '(JointC, 16)'}

... which undoubtedly is a dictionary. 

In order to use `vapor_master` as a true drop-in replacement, these things must be consistent.

**Comment by sevenbitbyte** [comment]
Fix has been merged and is now available in the [snap store as version `0.3`](https://snapcraft.io/vapor-master)
